# =============================================================================
# Cloud Build Configuration for LLM Observability Copilot
# =============================================================================
# This file defines the CI/CD pipeline for Google Cloud Build
#
# Trigger this build:
#   gcloud builds submit --config cloudbuild.yaml
#
# Or set up a trigger in Cloud Console for automatic deployments
# =============================================================================

steps:
  # ---------------------------------------------------------------------------
  # Step 1: Build Docker image
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '.'
    id: 'build-image'

  # ---------------------------------------------------------------------------
  # Step 2: Push to Artifact Registry
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
    id: 'push-image-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
    id: 'push-image-latest'
    waitFor: ['build-image']

  # ---------------------------------------------------------------------------
  # Step 3: Deploy to Cloud Run
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'DD_SERVICE=${_SERVICE_NAME},DD_ENV=production,DD_VERSION=${SHORT_SHA}'
      - '--set-secrets'
      - 'DD_API_KEY=dd-api-key:latest,DD_APP_KEY=dd-app-key:latest'
    id: 'deploy-cloud-run'
    waitFor: ['push-image-sha']

# -----------------------------------------------------------------------------
# Substitution Variables (can be overridden)
# -----------------------------------------------------------------------------
substitutions:
  _SERVICE_NAME: llm-observability-copilot
  _REGION: us-central1
  _REPOSITORY: llm-copilot-repo

# -----------------------------------------------------------------------------
# Build Options
# -----------------------------------------------------------------------------
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# -----------------------------------------------------------------------------
# Images to store in Artifact Registry
# -----------------------------------------------------------------------------
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

# -----------------------------------------------------------------------------
# Build timeout (default is 10 minutes)
# -----------------------------------------------------------------------------
timeout: '1200s'

